### ISSUE TITLE
Make nginx's `worker_processes` configurable

### ISSUE THREAD

**Issue by ruurtjan** [evertramos/nginx-proxy-automation#141]
First off, thanks for open sourcing this. It's very useful!

# Error description:
Some nginx configurations, like `worker_processes` can only be set in `/etc/nginx/nginx.conf`. If added to the `conf.d` folder, as suggested by the read me, an error occurs: `"worker_processes" directive is not allowed here in [...]`.

# Current workaround
For the time being I've updated the `docker-compose.yml`. I've added this line to `nginx-web`:
```
    command: /bin/bash -c "sed -i 's/worker_processes  1;/worker_processes  2;/' /etc/nginx/nginx.conf && nginx -g \"daemon off;\""
```
This launches nginx [just like the original image would](https://github.com/nginxinc/docker-nginx/blob/97b65112180e0c7764465aa47a974fc7af3c99ae/mainline/stretch/Dockerfile), but first updates the config in place.

# Suggested improvement
There are probably two ways to move forward:

1. Add a specific option to set the number of worker processes in `.env`.
2. Add an option to update `/etc/nginx/nginx.conf` in a more general way.

Would love to hear your thoughts on this.

**Comment by evertramos** [comment]
Hello @rriemann!!!

Thanks for your comments. I really like the idea of having this option, in fact I am not really into nginx settings... so, this was pretty new to me (_worker_process_), but I have read the nginx docs and think that should really has an option in our repo. 

I am more into docker, linux server admin, bash scripting etc...

So, I the option number **1** is what we can do for now in our repo, right? Once the option number 2 should be done by @jwilder... the owner of the nginx knowledge....

I haven't really tested it yet, would you like to send a PR? I would really be glad to have your help on that, I would test it and push to master right the way.

Thank you very much for your time to send us this issue and help others to improve this proxy.

**Comment by pgassmann** [comment]
Using a `docker-compose.override.yml` https://docs.docker.com/compose/extends/ it is possible to mount the nginx.conf without changing any repository or docker image content.

**Comment by ruurtjan** [comment]
@pgassmann That's indeed better than my current workaround. Adding `docker-compose.override.yml` would improve extensibility, so is a good idea regardless of the issue at hand IMHO.

I think we can avoid adding logic to our scripts, and simply update the readme with this suggestion.  The only down side is that you'd have to keep a local copy of the entire `nginx.conf`, which might get out of date with later versions of nginx.

On the other hand, settings like `worker_processes` may only be defined once, so adding a layer to the image in which we append settings to the config woun't do. You'd have to get smart about what settings to add, and which to replace. Replacing the entire config seems like the pragmatic choice here.

**Comment by perarg** [comment]
@pgassmann i think it is /etc/**nginx**/nginx.conf

**Comment by pgassmann** [comment]
@perarg Thanks. I fixed it in the snippet.
