### ISSUE TITLE
realip.conf not working

### ISSUE THREAD

**Issue by teminvictus** [evertramos/nginx-proxy-automation#150]
I have trouble setting up real.conf. It just doesn't seem to work.
I did read some related issues, specially #53 where it seems its working for some guys. 

I did try a couple of versions:

```
set_real_ip_from  172.18.0.0/32;

header X-Forwarded-For;
```

```
set_real_ip_from  172.18.0.0/32;

real_ip_header X-Real-IP;
```

```
real_ip_header X-Real-IP;
real_ip_recursive on;
```

Pretty sure I did all the combos you can do with it. But still the real ip won't get through.
Also to my to my knowledge it should work with both X-Forwarded-For and X-Real-IP in same block.

One thing I don't get at all, shouldn't there be changes in my default.conf when I change something in the real.conf? (of course after a restart of nginx-web container) I can't see any.

Maybe my understanding is to basic, but shouldn't there be changes in the location section.
Here is my default.conf when starting the container with the start.sh script:

```
# xxx.xxx.com
upstream xxx.xxx.com {
                                ## Can be connected with "webproxy" network
                        # xxx
                        server 172.18.0.7:80;
}
server {
        server_name xxx.xxx.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name xxx.xxx.com;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA$
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/xxx.xxx.com.crt;
        ssl_certificate_key /etc/nginx/certs/xxx.xxx.com.key;
        ssl_dhparam /etc/nginx/certs/xxx.xxx.com.dhparam.pem;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/certs/xxx.xxx.com.chain.pem;
        add_header Strict-Transport-Security "max-age=31536000" always;
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://xxx.xxx.com;
        }
}
```

So again I would think it would need to be something like:

```
# xxx.xxx.com
upstream xxx.xxx.com {
                                ## Can be connected with "webproxy" network
                        # xxx
                        server 172.18.0.7:80;
}
server {
        server_name xxx.xxx.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name xxx.xxx.com;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA$
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/xxx.xxx.com.crt;
        ssl_certificate_key /etc/nginx/certs/xxx.xxx.com.key;
        ssl_dhparam /etc/nginx/certs/xxx.xxx.com.dhparam.pem;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/certs/xxx.xxx.com.chain.pem;
        add_header Strict-Transport-Security "max-age=31536000" always;
        include /etc/nginx/vhost.d/default;
        set_real_ip_from 10.0.0.0/8;
        real_ip_header X-Real-IP;
        real_ip_recursive on;
        location / {
                proxy_pass http://xxx.xxx.com;
                proxy_set_header  Host $host;
                proxy_set_header  X-Real-IP $remote_addr;
                proxy_set_header  X-Forwarded-For $remote_addr;
        }
}
```

thanks guys

**Comment by evertramos** [comment]
Hello @teminvictus,

Did you manage to solve it?

If you set it on the [realip.conf](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/conf.d/realip.conf) file it will be loaded by nginx, but not in the default.conf file. 

When checking the nginx configurations loaded you will see the real ip there:

```bash
$ docker exec -it nginx-web nginx -T
```

You must check the logs of the nginx-web and the container forwared to see if the ip is being passed... one think I have done to prove that it is working, load up a new nginx container to receive the connection from the proxy and log the ip address or real ip header set in your conf. You will see the ip address in the log will be the origin ip addres.

Hope you already got through it.

Cheers!

Sorry my late reply...

**Comment by teminvictus** [comment]
Sorry I wasn't able to look into that issue earlier.

So when I do "docker exec -it nginx-web nginx -T" I see that my configuration is loaded correctly.
Strangely its working for one container right now, a few others not. all in the same ip range.

**Comment by j7an** [comment]
@teminvictus What do you get when running `docker network inspect` when running the containers that are not working?

**Comment by teminvictus** [comment]
What result are you wanting to get out of network inspect?

**Comment by evertramos** [comment]
@teminvictus did you manage to solve it? You might will need to restart the containers after enabling the options on realip.conf
