### ISSUE TITLE
CSR contains more than 100 DNS names

### ISSUE THREAD

**Issue by nalakawula** [evertramos/nginx-proxy-automation#159]
# Error description:
I got error when issue new cert

# Steps to reproduce
Just do as usual

# Expected result
Get my cert

# Error result
2019-07-24 08:36:16,908:INFO:simp_le:1479: Generating new certificate private key
ACME server returned an error: urn:acme:error:malformed :: The request message was malformed :: Error creating new cert :: CSR contains more than 100 DNS names

Debugging tips: -v improves output verbosity. Help is available under --help.
/app

# Comments
Any help?

Thanks

**Comment by unomind** [comment]
I know if the limit is 100. But if someone give me workaround to solve 100 limit, i will appreciate.

Thanks

**Comment by evertramos** [comment]
@nalakawula did you manage to work around this? I will close this issue once is not directly related to this project.
