### ISSUE TITLE
Question about a site without SSL

### ISSUE THREAD

**Issue by Liandirin** [evertramos/nginx-proxy-automation#179]
Is it possible to have one site behind the nginx and Lets encrypt proxy that does not use SSL? We have several sites behind an nginx and Lets encrypt reverse proxy using this docker container but for one of our sites we would like to be able to use normal unencrypted HTTP on port 80. Is that possible?

**Comment by evertramos** [comment]
It is possibel to have a site running on http only.. just do not add the letsencrypt variables (LETSENCRYPT_HOST and LETSENCRYPT_EMAIL) to your container.

If in the same container, with letsencrypt enabled, which the proxy forwards the request to, you have two domains, and you want one domain without ssl... this might be tricky to fix using this proxy... You might try traefik that can solve your issues on that.

**Comment by pgassmann** [comment]
@Liandirin If you want to use HTTP without redirect to HTTPS, you can disable the redirect using ENV:

`HTTPS_METHOD: noredirect`

https://github.com/jwilder/nginx-proxy#how-ssl-support-works
