### ISSUE TITLE
IPv6: Handle it correctly, no NAT

### ISSUE THREAD

**Issue by samip5** [evertramos/nginx-proxy-automation#190]
# Error description:
Container unable to see IPv6 IP address and as result ip restrictions not working.

# Steps to reproduce
Have IPv6 enabled on host.

# Expected result
App container sees IPv6 address and policies would work correctly.

# Comments
There should be NO NAT for IPv6, period and it should use an actual prefix, which could be asked in .env files.
https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/7cab8d8b8b0884fe548dd189233a00088e5331d1/start.sh#L17-L18 BIG NO on the NAT.

**Comment by evertramos** [comment]
Please try the new version (v0.5), in case of error open a new issue. Thanks!

use the option '--activate-ipv6'
