### ISSUE TITLE
Custom location proxy_pass parameter for nginx

### ISSUE THREAD

**Issue by Unclezz** [evertramos/nginx-proxy-automation#191]
Hello, 

I am trying to run a mail server solution (mailu.io) where the admin panel and the webmail are behind a folder, like:

www.my_mail_server.com/admin
www.my_mail_server.com/webmail

according to mailu.io documentation, one step to properly configure the service while being behind reverse proxy, is to pass to nginx in "server", some options like this:

location /webmail {
    proxy_pass https://localhost:8443/webmail;
  }

Is there any way to have such parameter passed to NGINX using this git repo?

Thanks!

**Comment by evertramos** [comment]
Hello @Unclezz...

I really missed that, and I am sorry. If you still need help with that please open a discussion with this subject and we will work on it. 

Thanks!
