### ISSUE TITLE
Let's encrypt failures

### ISSUE THREAD

**Issue by Unclezz** [evertramos/nginx-proxy-automation#195]
# Error description:
NGINX cannot

# Steps to reproduce
Simply restart the nginx-proxy companion and restart any wordpress or nextcloud from this same repo author.

# Expected result
reach the webservices via HTTPS

# Error result
From docker container nginx-letsencrypt:

nginx-letsencrypt    | 2020-03-06 18:24:54,102:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3200719849, https://acme-v02.api.letsencrypt.org/acme/authz-v3/3200719850, https://acme-v02.api.letsencrypt.org/acme/authz-v3/3200719851
nginx-letsencrypt    | Challenge validation has failed, see error log.

# Comments
Happening on Debian10, apparently after the upgrade o docker-cli, but not 100% sure if related.

**Comment by Kyouuma** [comment]
i stumbled across the same issue. 
This is not a permanent fix: I ran each container separately in this order web-proxy -> letsencrypt-nginx-proxy-companion ->  nginx-gen -> my websites.
and i did it using a root account. 
this was only done in an attempt to pinpoint the issue. I will propose a fix once i fully understand what happened.

**Comment by evertramos** [comment]
I use ubuntu and tested this restart a couple times works fine... not sure why would be different from debian. Are you using the latest version of jwilder container? 

`./start.sh` would update it.

**Comment by Kyouuma** [comment]
i don't think this is related to jwilder container as i did use the latest version. if i run my projects and your docker compose together that error occurs. It only works for me if i run them one by one

**Comment by evertramos** [comment]
doesn't make sense... I have being very busy in covid issues... but will try some debian server to see it.

I had an old centos backup I tried and the docker compose does not work with the latest packages "approved" by the centos official apt source list... but the containers ran smothly with manual docker-compose build. 

I will get debian to check, but debian should work smothly in that matter as well... not sure what would cause that.

**Comment by pythrick** [comment]
I'm having the same issue here 😢

**Comment by Olawale1** [comment]
Hi ,

I can confirm the same issue as well (Ubuntu 18.04 LTS). Had to use the workaround suggested by @Kyouuma in order to get things running. I also noticed the web-proxy seems to have problems starting when I add multiple conf files at once... It works when I add them one after the other though

Kind regards,

**Comment by pythrick** [comment]
I really appreciate the time this tool help me out, but it's time to move forward. I'm using Traefik as my reverse proxy tool.

**Comment by Olawale1** [comment]
Just as an update, I found that the issue (in my case) was caused by the extra nginx conf files not being properly configured. Once this was sorted and nginx reloaded, things became much more steady... except for needing to run the start script more than once occasionally

Thanks

**Comment by evertramos** [comment]
Please try the new version (v0.5), in case of error open a new issue. Thanks!
