### ISSUE TITLE
Trouble running on Raspberry PI

### ISSUE THREAD

**Issue by ghost** [evertramos/nginx-proxy-automation#199]
# Error description:

I have tried running proxy on mac and it works like a charm. But when I run it on Raspberry PI (arm architecture). I am having troubles.

# Steps to reproduce

1. Run `./start.sh`
2. Run `docker run -d -e VIRTUAL_HOST=test --network=webproxy --name my_app httpd:alpine`
3. Edit hosts file and add a line there: `127.0.0.1 test`
4. Run `curl test`

# Expected result

Get a 200 reply from server

# Error result

`curl: (56) Recv failure: Connection reset by peer`

# Comments

1. Container jwilder/docker-gen is always failing and being restarted with a following line showing in logs: `standard_init_linux.go:207: exec user process caused "exec format error"`
2. No logs for nginx container.

Any ideas?

**Comment by evertramos** [comment]
Well Dude, in this case you will need to check docker version, kernel... etc but it should work as well. Never tried that though. The containers are running? Check the log on creating them to see what could it be. Did you check this line in the go code to see? might need some more extra packages in this RPi

**Comment by dealancer** [comment]
@evertramos 

The only running containers are nginx-web and nginx-letsencrypt, nginx-gen is stopped and always try to restart. See my comments earlier.

Here are versions:

```
Docker version 18.09.3, build 774a1f4
docker-compose version 1.23.2, build 1110ad0
4.15.0-1057-raspi2
```

Logs:

```
docker-compose logs
Attaching to nginx-letsencrypt, nginx-web, nginx-gen
nginx-letsencrypt    | Info: Creating Diffie-Hellman group in the background.
nginx-letsencrypt    | A pre-generated Diffie-Hellman group will be used for now while the new one
nginx-letsencrypt    | is being created.
nginx-letsencrypt    | Generating DH parameters, 2048 bit long safe prime, generator 2
nginx-letsencrypt    | Reloading nginx docker-gen (using separate container nginx-gen)...
nginx-letsencrypt    | Reloading nginx (using separate container c82929556b1e348f95e7d2ae3a28f038252df7c6fbb520285d3829c66a782c7d)...
nginx-gen            | standard_init_linux.go:207: exec user process caused "exec format error"
nginx-letsencrypt    | Sleep for 3600s
nginx-gen            | standard_init_linux.go:207: exec user process caused "exec format error"
nginx-letsencrypt    | 2020/04/02 01:50:36 Generated '/app/letsencrypt_service_data' from 3 containers
nginx-gen            | standard_init_linux.go:207: exec user process caused "exec format error"
nginx-letsencrypt    | 2020/04/02 01:50:36 Running '/app/signal_le_service'
nginx-letsencrypt    | 2020/04/02 01:50:37 Watching docker events
nginx-letsencrypt    | Sleep for 3600s
nginx-letsencrypt    | 2020/04/02 01:50:38 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx-letsencrypt    | 2020/04/02 01:50:38 Received event die for container 2fed7e5300df
nginx-letsencrypt    | 2020/04/02 01:50:53 Debounce minTimer fired
nginx-letsencrypt    | 2020/04/02 01:50:53 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service
```

I haven't checked this line in code, not sure how I can fix it.

**Comment by dealancer** [comment]
@evertramos I do not see any arm versions of the docker-gen images: https://hub.docker.com/r/jwilder/docker-gen/tags - do you think that could be a problem?

**Comment by dealancer** [comment]
@evertramos ok, I have figured it out, it was docker-gen problem. Since there are no armhq builds on DockerHub, I have built an armhq image by myself and it worked. I want my change to be included into these project but there is a double step process.

1. @jwilder reviews and approves PR for https://github.com/jwilder/docker-gen/issues/321
2. I create a PR for this project and then you can review and approve it

For now my change looks like this:

```
  nginx-gen:
    build:
      context: https://github.com/dealancer/docker-gen.git
      args:
        - ARCHITECTURE=armhf
```

`armhf` could potentially be moved into .env file. Alternatively we can provide a documentation on how to run this project on RPI.

**Comment by evertramos** [comment]
Please try the new version (v0.5), in case of error open a new issue. Thanks!
