### ISSUE TITLE
way to include nginx-ultimate-bad-bot-blocker

### ISSUE THREAD

**Issue by teminvictus** [evertramos/nginx-proxy-automation#212]
hi guys, 
first thanks for providing this project here on GitHub.
you see a way to include https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker ?

thanks,
cheers

**Comment by evertramos** [comment]
Please try the new version (v0.5), in case of error open a new issue. Thanks!

You might want to open a discussion for that.
