### ISSUE TITLE
error 500, use self-signed certs if letsencrypt verification does not work

### ISSUE THREAD

**Issue by maichai** [evertramos/nginx-proxy-automation#222]
# Error description: 
When connecting with HTTPS nginx gives 500 Internal Server Error

# Steps to reproduce: 
connect with HTTPS 

# Expected result: 
in my case Portainer should be shown (this properly works for HTTP on port 80)

# Error result 
not sure what you are asking...

# Comments
I know that the letsencrypt verification does not work because ports 80 and 443 are not reachable from the internet. However, while this is the case I have created certificates using mkcert and provided them with the portainer env for docker-portainer-letsencrypt:

```
CONTAINER_NAME=portainer
PORTAINER_DATA_PATH=/mnt/appdata/portainer
ADMIN_PASSWORD=.....
DOMAINS=domainA,domainB
MAIN_DOMAIN=domainA
LETSENCRYPT_EMAIL=....
PORTAINER_SSL_PATH=/mnt/appdata/nginx-data/certs
PORTAINER_SSL_CERTIFICATE=$PORTAINER_SSL_PATH/$MAIN_DOMAIN.crt
PORTAINER_SSL_KEY=$PORTAINER_SSL_PATH/$MAIN_DOMAIN.key
NETWORK=webproxy
```

the environment for docker-compose-letsencrypt-nginx-proxy-companion looks as follows:

```
NGINX_WEB=nginx-web
DOCKER_GEN=nginx-gen
LETS_ENCRYPT=nginx-letsencrypt
IP=172.25.10.10    # could I actually use 0.0.0.0 here so allow connection to any interface? there is only 1 interface.
NETWORK=webproxy
NGINX_FILES_PATH=/mnt/appdata/nginx-data
```
Reading the nginx-proxy documentation I found this: 
> A self-signed or generic cert named default.crt and default.key will allow a client browser to make a SSL connection (likely w/ a warning) and subsequently receive a 500.

So possibly the experienced behavior is as specified. Would I be possible to configure nginx to not complain with a error 500 for self-signed certificates?

Someone might be tempted to point me to use nginx-proxy directly, which is not really what I want: I would like to make a setup that works with letsencrypt in case ports 80/443 are exposed to the internet, and also works in a internal scenario, when the ports are not exposed to the internet.

Is there a way this can be configured to work in both cases? (letsencrypt for internet exposed, and mkcert/manually provided certs if not exposed to the internet)

**Comment by nffdiogosilva** [comment]
Any update on this?

**Comment by evertramos** [comment]
I would need some more details, logs and how the cert was configured...
