### ISSUE TITLE
Different Locations for one server (routing)

### ISSUE THREAD

**Issue by rednag** [evertramos/nginx-proxy-automation#224]
# Error description:
Feature request

# Steps to reproduce
None

# Expected result
Add different locations for one server

# Error result
None

# Comments
I'd like to use different locations for routing more than one webserver over one ddns address. If I'm changing the location in the default.conf it is overwritten, so where to set it?

**Comment by Olawale1** [comment]
Hi @rednag 

You can add it in the vhost.d/conf file

Cheers

**Comment by Olawale1** [comment]
Hi @rednag 

You can add it in the vhost.d/default file

Cheers
