### ISSUE TITLE
How to create custom networks?

### ISSUE THREAD

**Issue by whackur** [evertramos/nginx-proxy-automation#225]
I have read **.env** options. but It is insufficient understand how to use it.

I activate options

```shell script
SERVICE_NETWORK=webservices
SERVICE_NETWORK_OPTIONS="--opt encrypted=true"
```

My docker-compose.yml file
```shell script
version: '3.8'

services:
  maria-db:
    image: mariadb:latest
    container_name: example-maria-db
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wpdb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    network_mode: "webservices"

  wordpress:
    depends_on:
      - maria-db
    image: wordpress:latest
    container_name: example-wp
    restart: always
    volumes:
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: maria-db:3306
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: admin@gmail.com
    network_mode: "webservices"

networks:
  default:
    external:
      name: webservices
```

I create 'webservice' docker network.
Currently,
```shell script
NETWORK ID          NAME                DRIVER              SCOPE
2b706d5bc02d        bridge              bridge              local
56cf1c518cf1        host                host                local
92ee611c03f4        none                null                local
100fb8e9fe06        webproxy            bridge              local
a184a94ed5f2        webservices         bridge              local

```

When i docker-compose up, I can see network resolve error "MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known".

I think DB connection failed.

and I can curl localhost in wordpress container, but can not connect to web-site 'example.com'

How to create custom network?

For example.

webproxy  : default network
webservices1 : custom isolation network from 'webproxy' and connected webservices1 network each other.
webservices2 : custom isolation network from 'webproxy' and connected webservices2 network each other.

**Comment by evertramos** [comment]
If you intend to use this proxy you must add the proxy network to you Wordpress service. Please check our Wordpress setup in the readme. If you quiet don't understand the env file, check the Docker docs to see how you can create a network but make sure you have the proxy network connected to the Wordpress container in order to proxy your connections.
