### ISSUE TITLE
How can we setup it to upload large file?

### ISSUE THREAD

**Issue by cod3r0k** [evertramos/nginx-proxy-automation#230]
# Error description:
gitlab error 413 (big file can't be uploaded). How can we setup nginx to upload large file?

**Comment by evertramos** [comment]
might be... enable the nginx conf and set your max file upload. make sure you have the same settings in your local application set up.

**Comment by gustawdaniel** [comment]
This is third issue in this topic:

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/issues/207
https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/issues/81

I have this problem too some times. We should add chapter in documentation that explains possible 
solutions and best practices of solving this problem.

**Comment by pathros** [comment]
In the previous version, inside the .env file, you could enable additional Nginx variables config by uncommenting the following line:

`#USE_NGINX_CONF_FILES=true`

which allowed Nginx to include those 3 config files, inside this [conf.d/](https://github.com/evertramos/nginx-proxy-automation/tree/master/conf.d) folder:

- realip.conf. It sets a group of IP addresses as real.
- servertokens.conf. It disables display the nginx version in web browsers. 
- uploadsize.conf. Sets the max uploading size to 100MB.

Enabling the _uploadsize.conf_ file was enough to avoid that "Entity Too Large" error.

But now in this new version, I can't find how to include that _uploadsize.conf_ file, which is still included in this new version repo.

Any ideas how to include those config files, or how to increase the `client_max_body_size` variable?
