### ISSUE TITLE
CORS Headers do not work

### ISSUE THREAD

**Issue by steinbachio** [evertramos/nginx-proxy-automation#243]
# Error description:
According to http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header adding `add_header 'Access-Control-Allow-Origin' * always;` should result in working CORS on 500 response codes.

500 Response codes are not forwared.

# Steps to reproduce
Add `add_header 'Access-Control-Allow-Origin' * always;` to nginx.tmpl and produce a 500 response code on the webserver behind the proxy.

# Expected result
seeing the 500 error in the client

# Error result
Access to XMLHttpRequest at from origin has been blocked by cors policy

**Comment by evertramos** [comment]
did you manage to fix it? this should go to nginx-proxy repo....
