### ISSUE TITLE
Question: 'Failure website' showing for all 'wrong' addresses?

### ISSUE THREAD

**Issue by fribse** [evertramos/nginx-proxy-automation#247]
# Error description:
We have a wildcard cname for this, so that one could access it from all subdomains under that host.
But if somebody misspells it, they get a certificate signed by CN=letsencrypt-nginx-proxy-companion.

Would it be possible to have some sort of 'catch-all' website that will catch none-configured hostnames.
So if you have
12345.cname.wildcard.com you will be shown the right website
and you mistype maybe like
23456.cname.wildcard.com
they would get a 'default' website.

**Comment by evertramos** [comment]
Hello @fribse I have never tried... would you please share if you accomplish to do that? I would like to add it to the docs.
