### ISSUE TITLE
Question: Do you plan update reflecting the switch to acme.sh?

### ISSUE THREAD

**Issue by thorewi** [evertramos/nginx-proxy-automation#248]
Hi,

I've noticed that https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion switched to acme.sh, what's imho not reflected in this package. Do you plan to update it? Thank you.

**Comment by evertramos** [comment]
Yes I do. I have a full server automation script related to this script which need to be checked there are bunch of automated process which I also plan do open source it next quarter. Hope to get through it soon. Sorry my absence.

**Comment by thorewi** [comment]
Great! Is it possible to support you somehow to get this update as soon as possible? I've noticed you removed Beerpay recently.

**Comment by evertramos** [comment]
Hello @thorewi  are you able to test it as well?

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/tree/v2

I will open a patreon soon, but I have paypal! =)

**Comment by thorewi** [comment]
Should I test something special or just follow the readme?

**Comment by evertramos** [comment]
for now just test the compose file if you would

**Comment by evertramos** [comment]
Done!
