### ISSUE TITLE
I have problems uploading a laravel api 111: Connection refused 

### ISSUE THREAD

**Issue by Irimax** [evertramos/nginx-proxy-automation#249]
I have an error 1 connect () failed (111: Connection refused) while connecting to upstream, client: 172.18.0.5, server: laravel-api.art, request: "GET / HTTP / 1.1", upstream: "fastcgi: //172.18.0.19: 9000 ", host:" laravel-api.art "172.18.0.5

I can't get it to work here is my nginx conf file

`upstream upstream-nginx-web {
    server laravel-api:9000;
}

server {
    listen 80;
    server_name  laravel-api.manoha.art;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/public;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi.conf;
        fastcgi_pass laravel-api:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        proxy_pass http://upstream-nginx-web;
    }
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        root /var/www/public;
        gzip_static on;
    }
}

`

**Comment by evertramos** [comment]
@Irimax sorry my late reply... I was not able to test it. Did you manage to fix it?

did you use the VIRTUAL_PORT=9000 in your docker-compose for Laravel?

**Comment by Irimax** [comment]
no I still haven't solved my problem no I tried port 9000 but not VIRTUAL_PORT or should I put it

**Comment by evertramos** [comment]
I can remove it form the 'ports' directive and add an env variable 'VIRTUAL_PORT=9000' to your compose file and try again.

**Comment by evertramos** [comment]
I will update this with my new version using nginx with Laravel, but this is the basic idea:

https://github.com/evertramos/docker-laravel/blob/master/Dockerfile

**Comment by Irimax** [comment]
I added the virtual host 9000 but it doesn't work

here is my dockerFile

`FROM php:7.4-fpm

COPY composer.lock composer.json /var/www/

WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libzip-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    nano \
    curl

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_mysql  zip exif pcntl
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install gd

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel
RUN groupadd -g 999 www
RUN useradd -u 999 -ms /bin/bash -g www www

# Copy application folder
COPY . /var/www

# Copy existing permissions from folder to docker
COPY --chown=www:www . /var/www
RUN chown -R www-data:www-data /var/www

# change current user to www
USER www

EXPOSE 9000
CMD ["php-fpm"]


# production environment
FROM nginx:stable-alpine
RUN rm /etc/nginx/conf.d/default.conf
#COPY nginx/nginx.conf /etc/nginx/conf.d
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`

**Comment by evertramos** [comment]
@Irimax in order to use PHP-fpm directly with this proxy you will have to take a look at the nignx-proxy settings at:

https://github.com/nginx-proxy/nginx-proxy#fastcgi-backends

Or you could create an nginx with this settings to work along with this php-fpm container, but definetly this is not a bug on this script/project.
