### ISSUE TITLE
Hide server header

### ISSUE THREAD

**Issue by AndreSouzaAbreu** [evertramos/nginx-proxy-automation#251]
# Error description:

It is not possible to hide the `Server` header, even after adding the module `http-headers-more` ( `apk add nginx-mod-http-headers-more`) and setting `more_clear_headers Server;` in `/etc/nginx/nginx.conf`. I believe this is because the version of nginx that is running is uncompatible with the version of the module. There is [a similiar issue on StackOverflow](https://stackoverflow.com/questions/59988807/how-to-install-a-module-on-nginx)

# Steps to reproduce

Run

```shell
docker exec -it nginx-web sh
apk add nginx-mod-http-headers-more
```

Edit `nginx.conf` to be like this

```nginx
load_module /etc/nginx/modules/ngx_http_headers_more_filter_module.so;

user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

    # hide server head
    more_clear_headers Server;
}
```

# Expected result

The header `Server` won't appear in response headers.

# Error result

Trying to reload nginx with `nginx -s reload` gives the error

```
emerg] 60#60: module "/etc/nginx/modules/ngx_http_headers_more_filter_module.so" version 1016001 instead of 1018000 in /etc/nginx/nginx.conf:1
nginx: [emerg] module "/etc/nginx/modules/ngx_http_headers_more_filter_module.so" version 1016001 instead of 1018000 in /etc/nginx/nginx.conf:1
```

# Comments

Can you please help me disable this header?

**Comment by evertramos** [comment]
I suggest you create a Dockerfile starting from nginx and make all the instalation you need. After that you must update the nginx.tmpl in the root of this project or check the [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) itself. You might will find what you are looking for. If you need any assistance on that please contact me by email.
