### ISSUE TITLE
Issue with Gitlab SSH

### ISSUE THREAD

**Issue by syntaxgirl** [evertramos/nginx-proxy-automation#252]
I have created a Gitlab instance using their official way of creating it with docker. Everything works fine until I try to use ssh keys to clone, push, pull etc. Basically I didn't changed anything from the setup other than hostname etc.

When trying to do a test connection to gitlab this is log:

```
OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1i  8 Dec 2020
debug1: Reading configuration data /home/xyz/.ssh/config
debug1: /home/xyz/.ssh/config line 1: Applying options for *
debug1: /home/xyz/.ssh/config line 63: Applying options for xyz.com
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolving "gitlab.xyz.com" port 443
debug2: ssh_connect_direct
debug1: Connecting to gitlab.xyz.com x.x.x.x] port 443.
debug1: Connection established.
debug1: identity file /home/xyz/.ssh/id_rsa.pub type 0
debug1: identity file /home/xyz/.ssh/id_rsa.pub-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.2
debug1: kex_exchange_identification: banner line 0: HTTP/1.1 400 Bad Request
debug1: kex_exchange_identification: banner line 1: Server: nginx/1.18.0
debug1: kex_exchange_identification: banner line 2: Date: Fri, 12 Mar 2021 15:50:00 GMT
debug1: kex_exchange_identification: banner line 3: Content-Type: text/html
debug1: kex_exchange_identification: banner line 4: Content-Length: 157
debug1: kex_exchange_identification: banner line 5: Connection: close
debug1: kex_exchange_identification: banner line 6: 
debug1: kex_exchange_identification: banner line 7: <html>
debug1: kex_exchange_identification: banner line 8: <head><title>400 Bad Request</title></head>
debug1: kex_exchange_identification: banner line 9: <body>
debug1: kex_exchange_identification: banner line 10: <center><h1>400 Bad Request</h1></center>
debug1: kex_exchange_identification: banner line 11: <hr><center>nginx/1.18.0</center>
debug1: kex_exchange_identification: banner line 12: </body>
debug1: kex_exchange_identification: banner line 13: </html>
kex_exchange_identification: Connection closed by remote hos

```

If I try not to use ssh config file, I always get prompt to enter password for the git user. And also there is error
```
debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000)
```

Any idea what's the issue?

**Comment by evertramos** [comment]
Hello @syntaxgirl

Thanks for your post. 

I need to test all the way through as you did to see why this would happening, I have some questions on that:

- did you clone using https?
- when you push without ssh config file and asks for the password, you are able to push it?

When you connect to gitlab over nginx-proxy, the proxy will deal with ssl and forward a port 80 to gitlab container... not sure if this might be the error though...

**Comment by syntaxgirl** [comment]
@evertramos 
So when I try to clone with git and already have setup host inside config file, I get asked for the password. Same thing happen if I remove Host from config file (/home/xyz/.ssh/config)

Cloning with https, works perfectly. This is basically how we currently use gitlab (unfortunately). Pulling, pushing over https, works also. The only issue we are facing is via the ssh. Because of it, we can't setup properly the CI/CD Pipeline. Else than that, works perfectly.

Here is a debug from the following comamnd

`ssh -vvvT git@gitlab.example.com`

`OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1i  8 Dec 2020
debug1: Reading configuration data /home/xyz/.ssh/config
debug1: /home/xyz/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolving "gitlab.privadoa.com" port 22
debug2: ssh_connect_direct
debug1: Connecting to gitlab.privadoa.com [95.216.223.119] port 22.
debug1: Connection established.
debug1: identity file /home/xyz/.ssh/id_rsa type 0
debug1: identity file /home/xyz/.ssh/id_rsa-cert type -1
debug1: identity file /home/xyz/.ssh/id_dsa type -1
debug1: identity file /home/xyz/.ssh/id_dsa-cert type -1
debug1: identity file /home/xyz/.ssh/id_ecdsa type -1
debug1: identity file /home/xyz/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/xyz/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/xyz/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/xyz/.ssh/id_ed25519 type -1
debug1: identity file /home/xyz/.ssh/id_ed25519-cert type -1
debug1: identity file /home/xyz/.ssh/id_ed25519_sk type -1
debug1: identity file /home/xyz/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/xyz/.ssh/id_xmss type -1
debug1: identity file /home/xyz/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.2
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to gitlab.example.com:22 as 'git'
debug3: hostkeys_foreach: reading file "/home/xyz/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/xyz/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from gitlab.example.com
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,sk-ssh-ed25519@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:HmHPvtExrJ/1MLAvzUfydlFPvorK/s7765feAgyQFgA
debug3: hostkeys_foreach: reading file "/home/xyz/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/xyz/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from gitlab.example.com
debug3: hostkeys_foreach: reading file "/home/xyz/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/xyz/.ssh/known_hosts:2
debug3: load_hostkeys: loaded 1 keys from 95.216.223.119
debug1: Host 'gitlab.example.com' is known and matches the ECDSA host key.
debug1: Found key in /home/xyz/.ssh/known_hosts:1
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /home/xyz/.ssh/id_rsa RSA SHA256:4lX812ueTKcZ2WmiXz/mGvF8ED/Gu0EJLmfQt5iNKhk agent
debug1: Will attempt key: /home/xyz/.ssh/id_dsa 
debug1: Will attempt key: /home/xyz/.ssh/id_ecdsa 
debug1: Will attempt key: /home/xyz/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /home/xyz/.ssh/id_ed25519 
debug1: Will attempt key: /home/xyz/.ssh/id_ed25519_sk 
debug1: Will attempt key: /home/xyz/.ssh/id_xmss 
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug3: start over, passed a different list publickey,gssapi-keyex,gssapi-with-mic,password
debug3: preferred gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup gssapi-with-mic
debug3: remaining preferred: publickey,keyboard-interactive,password
debug3: authmethod_is_enabled gssapi-with-mic
debug1: Next authentication method: gssapi-with-mic
debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000)


debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000)


debug2: we did not send a packet, disable method
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/xyz/.ssh/id_rsa RSA SHA256:4lX812ueTKcZ2WmiXz/mGvF8ED/Gu0EJLmfQt5iNKhk agent
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Trying private key: /home/xyz/.ssh/id_dsa
debug3: no such identity: /home/xyz/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /home/xyz/.ssh/id_ecdsa
debug3: no such identity: /home/xyz/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /home/xyz/.ssh/id_ecdsa_sk
debug3: no such identity: /home/xyz/.ssh/id_ecdsa_sk: No such file or directory
debug1: Trying private key: /home/xyz/.ssh/id_ed25519
debug3: no such identity: /home/xyz/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: /home/xyz/.ssh/id_ed25519_sk
debug3: no such identity: /home/xyz/.ssh/id_ed25519_sk: No such file or directory
debug1: Trying private key: /home/xyz/.ssh/id_xmss
debug3: no such identity: /home/xyz/.ssh/id_xmss: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
git@gitlab.example.com's password:`

**Comment by evertramos** [comment]
@syntaxgirl in order to use ssh you must bind the port 22 of your host into your container, otherwise it will try to access the docker host port 22... so, if you plan to do that you might want to change the ssh port of your docker host (server running the docker) and then you will be able to bind port 22 to your gitlab container. Give it a try and let me know if it works. Through this proxy will only work over https.

**Comment by syntaxgirl** [comment]
> @syntaxgirl in order to use ssh you must bind the port 22 of your host into your container, otherwise it will try to access the docker host port 22... so, if you plan to do that you might want to change the ssh port of your docker host (server running the docker) and then you will be able to bind port 22 to your gitlab container. Give it a try and let me know if it works. Through this proxy will only work over https.

Thanks for this tip. So the way I did it, is I first added a new port for SSH on my server. Tested ssh with new port, worked. Then I removed port 22 from ssh on server. Once done, I just run gitlab image with
`docker run -p 22:22 ...`
and now everything works perfectly. For now this works. Though we have a different port for ssh now, but if it's the only way, it doesn't matter. In case you do have some tip to maybe still have both on port 22, let me know

**Comment by evertramos** [comment]
That's great you got it working! I have a personal ssh container that manages all ssh access to the server, but not for the host itself, it's like a bastion host, so clients can access their own wordpress sites over ssh without steping on the host itself, but never tested to forward it to gitlab... running the port 22 in the host and in the container I think it's not really an option. Also, I myself normally change the port 22 of a host, just to skip regular bots, so I consider a tiny good practice here.

Thanks for the reply!
