### ISSUE TITLE
ssl_policy environment variable is not applying

### ISSUE THREAD

**Issue by Zageron** [evertramos/nginx-proxy-automation#254]
# Error description:
Setting `SSL_POLICY=Mozilla-Modern` results in SSL_POLICY=Mozilla-Intermediate

# Steps to resolve
Modify line 115 in nginx.tmpl to default to Mozilla-Modern instead.
`{{ $ssl_policy := or ($.Env.SSL_POLICY) "Mozilla-Modern" }}`

# Expected result
Setting SSL_POLICY should properly override Mozilla-Intermediate defaults.

# Error result
ssllabs test results in a grade of B by default because of SNI.

**Comment by evertramos** [comment]
@Zageron I did the test below:

```bash
$ ./fresh-start.sh --skip-docker-image-check --yes -e YOUR_EMAIL_ADDRESS -sp "Mozilla-Modern"
```

And my result was:

![site_ssl_test](https://user-images.githubusercontent.com/905951/111821111-0e01d980-88c1-11eb-8fd7-a339d77f12ed.png)

Where did you check this issue? Can you give some more details?

**Comment by Zageron** [comment]
Using .env. I am away for a few days I'll send my config when I am able.

**Comment by evertramos** [comment]
@Zageron I will close for now... if you face any issues on that matter let me know.
