### ISSUE TITLE
nginx.tmpl doesn't include gzip options

### ISSUE THREAD

**Issue by Zageron** [evertramos/nginx-proxy-automation#255]
# Error description:
gzip cannot be enabled with configuration switches

# Expected result
Options during configuration should enable gzip.

# Manual Resolution
Modify nginx.tmpl near gzip_types to something similar to this:
```
gzip on;
gzip_min_length 250;
gzip_buffers  8 32k;
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
gzip_vary on;
gzip_proxied any;
```

**Comment by evertramos** [comment]
This repo is an automation of nginx-proxy, so please open this request at [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy)
