### ISSUE TITLE
invalid docker-compose file with ipv6

### ISSUE THREAD

**Issue by hanneshier** [evertramos/nginx-proxy-automation#256]
# Error description:
I just used the fresh-start.sh script setup nginx, but i get an error message all the time. I used the --activate-ipv6 flag

# Steps to reproduce
Install the container following the readme.md procedure.
Start the setup with ```bin/fresh-start.sh --activate-ipv6```

# Expected result
Working nginx-reverse-proxy

# Error result

```
ERROR: The Compose file '/home/hannes/proxy/bin/../docker-compose.yml' is invalid because:
services.proxy-web-auto.ports is invalid: Invalid port "::/0:443:443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.proxy-web-auto.ports is invalid: Invalid port "::/0:80:80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
>>> Success!
[end]-----------------------------------------------------------------

[ERROR]---------------------------------------------------------------
There was an error starting the service at '/home/hannes/proxy/bin/../'
----------------------------------------------------------------------
```

# Comments

**Comment by evertramos** [comment]
Please try to set your IPv6 addres and test it again.

**Comment by hanneshier** [comment]
Thank you! Its working now

**Comment by evertramos** [comment]
Ok! 

Issue fixed. You can try again from scratch it should work now. Let me know if you have any other issues.

**Comment by hanneshier** [comment]
I restarted the script from scratch and everything is working as it should. Thank very much for the quick fix!
