### ISSUE TITLE
fresh-start.sh error

### ISSUE THREAD

**Issue by emanuelerangan** [evertramos/nginx-proxy-automation#257]
# Error description:
I'm getting an error at the end of fresh-start.sh execution:
"There was an error starting the service at '/home/user/server/proxy/compose/bin/../'"

# Steps to reproduce
I followed the video tutorial step by step:
https://www.youtube.com/watch?v=E9BtHVr_v9I

# Expected result
Containers up and running

# Error result
.env file is created, but containers are not running.

# Comments

**Comment by evertramos** [comment]
@emanuelerangan could you please try again? We were fixing an (issue on basescript)[https://github.com/evertramos/basescript/issues/3] which was just fixed. Let me know.

**Comment by emanuelerangan** [comment]
Hi @evertramos, just tried, even after pulling the last version, I get the same error.

**Comment by evertramos** [comment]
@emanuelerangan I will need some more info to understand the error... what are the container logs? what is the error in the screen when running the script?

**Comment by emanuelerangan** [comment]
@evertramos Actually, the containers are not running after the fresh-start.sh execution.
Regardless of the output error
![image](https://user-images.githubusercontent.com/17144322/112556894-6fe3a700-8dcb-11eb-8254-bcfd9fb2a07b.png)
I've tried to start them with a `docker-compose up -d` (I also started up the test.sh container), and the logs are:

docker logs proxy-web-auto
![image](https://user-images.githubusercontent.com/17144322/112556129-d2d43e80-8dc9-11eb-85b9-b8ff68da5caf.png)

docker logs docker-gen-auto
![image](https://user-images.githubusercontent.com/17144322/112556138-d8ca1f80-8dc9-11eb-9b03-e5fac986ca64.png)

docker logs letsencrypt-auto
![image](https://user-images.githubusercontent.com/17144322/112556161-e2ec1e00-8dc9-11eb-9e1f-5410f81ea360.png)

docker logs test-web
![image](https://user-images.githubusercontent.com/17144322/112556570-c8667480-8dca-11eb-8915-1b9b7be58a50.png)


Nginx responds with a 503 HTTP status code, but no logs are provided under /vat/logs/nginx/error.log within the proxy-web-auto container


Also, here is the "git diff" and the .env file (without comments) produced after the fresh-start.sh execution:

![image](https://user-images.githubusercontent.com/17144322/112549673-73bcfc80-8dbe-11eb-9b38-c9d72158105f.png)

`NGINX_WEB_SEVICE_NAME=proxy-web-auto
NGINX_IMAGE_VERSION=stable-alpine
DOCKER_GEN_SEVICE_NAME=docker-gen-auto
DOCKER_GEN_IMAGE_VERSION=0.7.3
LETS_ENCRYPT_SEVICE_NAME=letsencrypt-auto
NGINX_PROXY_COMPANION_IMAGE_VERSION=2.0
NETWORK=proxy
NGINX_FILES_PATH=/home/emanuele/server/proxy/data
NGINX_WEB_LOG_DRIVER=json-file
NGINX_WEB_LOG_MAX_SIZE=4m
NGINX_WEB_LOG_MAX_FILE=10
NGINX_GEN_LOG_DRIVER=json-file
NGINX_GEN_LOG_MAX_SIZE=2m
NGINX_GEN_LOG_MAX_FILE=10
NGINX_LETSENCRYPT_LOG_DRIVER=json-file
NGINX_LETSENCRYPT_LOG_MAX_SIZE=2m
NGINX_LETSENCRYPT_LOG_MAX_FILE=10
DOCKER_HTTP_=80
DOCKER_HTTPS=443
SSL_POLICY=Mozilla-Intermediate
DEFAULT_EMAIL=********@gmail.com`

For any further info, please ask me.

**Comment by evertramos** [comment]
@emanuelerangan thanks for all logs... could you please send me the error on the script full page? I need to know where in the script it stopped... in your print does not show the last function it ran.

have you tried to start from scratch again?

**Comment by emanuelerangan** [comment]
Hi @evertramos, thanks for your support on this!

I've removed the containers and checked out the repository from scratch. Here are the logs screenshots about the fresh-start.sh execution:
[fresh-start.zip](https://github.com/evertramos/nginx-proxy-automation/files/6214865/fresh-start.zip)
I also tried running fresh-start.sh as sudo, but the results are identical.

My docker installation under /usr/bin is owned by root:root
![image](https://user-images.githubusercontent.com/17144322/112705546-ac80d280-8e9f-11eb-827c-e58a25c44fd0.png)
![image](https://user-images.githubusercontent.com/17144322/112705508-780d1680-8e9f-11eb-97d2-e11386fd32d2.png)
It's a home server based on ubuntu 18.04 and has public ip.

Don't hesitate to ask for any other info you need.

**Comment by evertramos** [comment]
@emanuelerangan I checked the script print and it seems there is an issue with docker-compose... could you please confirm the docker version and docker-compose version?

Also, would you please run again with the option `--debug` and send me only the last full print image with the function docker_compose_start ?

**Comment by emanuelerangan** [comment]
docker: 20.10.5
docker-compose: 1.23.2

I now upgraded to the latest docker-compose version (1.28.6) and it is working like a charm!

Thank you @evertramos for your support on this!

**Comment by leekheang** [comment]
my error md5sum: WARNING: 1 computed checksum did NOT match

**Comment by pathros** [comment]
I am getting the same error on CentOS 7.

I got this:
docker: 20.10.6
docker-compose: 1.29.1

I have even run it as root.

This is the error:

```
[ERROR]---------------------------------------------------------------
There was an error starting the service at '/... /proxy/bin/../'
----------------------------------------------------------------------
```

Any ideas on how to make it work?

**Comment by evertramos** [comment]
Hello @pathros,

You shouldn't run as root... try again following the video tutorial steps. It should work in CentOS 7 smothly as well.

**Comment by pathros** [comment]
Hello, again @evertramos .

I have managed to install Docker rootless and run the nginx proxy automation by executing the .fresh-start script.

However, now I get the following error for the `proxy-web-auto` container:

> ERROR: for proxy-web-auto  Cannot start service proxy-web-auto: driver failed programming external connectivity on endpoint proxy-web-auto (811c2b876077b2b6eaa4 .... 2b056a2eef394ddf1b3): Error starting userland proxy: error while calling PortManager.AddPort(): cannot expose privileged port 443, you can add 'net.ipv4.ip_unprivileged_port_start=443' to /etc/sysctl.conf (currently 1024), or set CAP_NET_BIND_SERVICE on rootlesskit binary, or choose a larger port number (>= 1024): listen tcp4 xxx.xxx.xxx.xxx:443: bind: permission denied
> ERROR: Encountered errors while bringing up the project.

What can I do to fix it and make it work?

**Comment by evertramos** [comment]
Hello @pathros 

Using rootless you still need some extra path to bind the some path into the container, so might be tricky... I will fix when have time a full tutorial on that as well. Only one server I am using rootless and it was kind of painful to make it fully working.

**Comment by pathros** [comment]
Hello, @evertramos ! 

I have applied this suggestion according to the Docker [rootless documentation](net.ipv4.ip_unprivileged_port_start=0) at the end of the `/etc/sysctl.conf` file:
`net.ipv4.ip_unprivileged_port_start=0`
I saved and exited. Then I applied the changes:
`sudo sysctl --system`.

So far so good.  the `fresh-start.sh` script executed flawlessly.

However, when I run a simple webpage with Docker using the proxy, now I get the following error in Firefox:

> PR_END_OF_FILE_ERROR

In Chrome:

> the webpage closed connection unexpectedly

Any ideas on how to fully make this Docker Rootless work with this proxy automation?
What am I missing?

**Comment by pathros** [comment]
Hello, again! @evertramos Evert!

I have found out how to add that extra path `$XDG_RUNTIME_DIR` , that is to say:
`DOCKER_HOST_ROOTLESS_PATH=/run/user/1000/docker.sock`
in the `docker-compose.yml` file and now it works!

I will send you my pull request.
