### ISSUE TITLE
Simplify setup

### ISSUE THREAD

**Issue by gustawdaniel** [evertramos/nginx-proxy-automation#259]
Version

https://github.com/evertramos/nginx-proxy-automation/tree/v0.4

was great because of only three commands was required to have working environment. Now script to start ask me about too many thinks that are not important and can be set by default.

I propose to reverse version 0.4 as main branch or at least type more docs about setup new version of script by single command without any user interaction. 

I would like to use it with ansible, terraform, digital ocean initial setups. In version 0.4 it was easy now is terrible.

**Comment by evertramos** [comment]
Hello @gustawdaniel!

Thanks for your comment. Would you start from scratch and try the following once again and let me know what you think:

At ./bin folder

'''bash
$ ./fresh-start.sh -e your-email@domain --yes
'''

**Comment by evertramos** [comment]
Closing for now, once it's not an issue... you might start a [discussion](https://github.com/evertramos/nginx-proxy-automation/discussions/new) on that subject.
