### ISSUE TITLE
[BUG] USE_NGINX_CONF_FILES=true not working

### ISSUE THREAD

**Issue by cod3rshotout** [evertramos/nginx-proxy-automation#272]
I'm getting 413 Request Entity Too Large when I try to upload an image of 3Mb, so I searched in the issues of this repo and I found this:

https://github.com/evertramos/nginx-proxy-automation/issues/81

first, I didn't have any USE_NGINX_CONF_FILES=true, so I manually added this line and executed this command:

docker-compose down -v
docker-compose up --build -d

I tried again to upload the image, and still the same problem.

**Comment by evertramos** [comment]
Please check my answer at this discussion:

https://github.com/evertramos/nginx-proxy-automation/discussions/261#discussioncomment-568310

**Comment by cod3rshotout** [comment]
Hi, for the second step I already have this file but same issue. Maybe because my docker application runs over nginx too?

Essentially I have nginx-proxy -> nginx -> PHP fpm

**Comment by evertramos** [comment]
yes you will neet to set this option in your own nginx too, in order to accept it.

please let me know if it worked.

**Comment by cod3rshotout** [comment]
@evertramos this is my app nginx service:

  nginx:
    image: nginx:stable-alpine
    container_name: app_nginx
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    environment:
      VIRTUAL_HOST: ${HOST}
      LETSENCRYPT_HOST: ${HOST}
      LETSENCRYPT_EMAIL: ${EMAIL}
      
inside the `nginx` folder I have this:

conf.d / default.conf:

     upstream php-upstream {
        server php-fpm:9000;
    }

sites / default.conf

    server {
        root   /var/www/html/public;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ [^/]\.php(/|$) {
            fastcgi_split_path_info ^(.+?\.php)(/.*)$;

            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO       $fastcgi_path_info;
            fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;

            fastcgi_pass   php-upstream;
            fastcgi_index  index.php;
        }
    }

nginx.conf:

    user  nginx;
    worker_processes  4;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        client_max_body_size 100M;

        access_log  /var/log/nginx/access.log;
        # Switch logging to console out to view via Docker
        #access_log /dev/stdout;
        #error_log /dev/stderr;

        sendfile        on;
        keepalive_timeout  65;
        
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-available/*.conf;
    }   

I tried to rebuild anything using `sudo docker-compose up --build -d` but same issue again, maybe am I missing something?

**Comment by cod3rshotout** [comment]
@evertramos I just did another test using per site config, so I have placed example.com_location under data/vhost.d with this:
client_max_body_size 100m;

then I have restarted the app and now works, but there is no way to manage this configuration to each sites? 'cause inside conf.d of nginx-proxy I have  uploadsize.conf which is supposed to be a global configuration, why I need to specify the site for make it working? I'm confused :\

**Comment by evertramos** [comment]
@cod3rshotout 

We have two options:

- Set this option in the nginx-proxy to allow the same max_body for all sites behind the proxy; or
- Set per site option as in the discussion #261 

In all cases your application will also need to allow this option.

In the Sever Automation script we will have this option automated in our WordPress environment... it will be open sourced in November.
