### ISSUE TITLE
Add reverse proxy option to config

### ISSUE THREAD

**Issue by lklic** [evertramos/nginx-proxy-automation#273]
**Is your feature request related to a problem? Please describe.**
Ability to reverse proxy a container to a specific address.

e.g. 
domain.com/app1 --> Docker container 1 port 8080
domain.com/app2 --> Docker container 2 port 8081

**Describe the solution you'd like**

Basically you need to inject something like  this into `proxy/data/conf.d/default.conf:`
```
location /app2 {
                proxy_pass http://app2:8081
        }

```
so the nginx template would need to be updated with some new variables.

**Comment by evertramos** [comment]
Please check [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) for more information related to nginx template and options.

**Comment by evertramos** [comment]
@lklic you can also put a nginx behind this proxy and do your proxy forward option.

**Comment by lklic** [comment]
This was just a feature request to make it more simple when using your scripts. I know you can configure this manually. 

There seemed to be a lot of interest in it since this issue has been opened up several times in the past. 

Anyways, very handy set of scripts, nice work!
