### ISSUE TITLE
[BUG] Certs Created Already Expired

### ISSUE THREAD

**Issue by stvhanna** [evertramos/nginx-proxy-automation#279]
**Check [Discussions](https://github.com/evertramos/nginx-proxy-automation/discussions) to see if there is an answer might help you before opening an issue**

**Describe the bug**
Using latest from master, the certificate being created is already expired. See log below. There's no firewall or otherwise a blocker preventing the connection. On a previous version of master, it worked fine.

**To Reproduce**
1. Go to https://sub.domain.com
2. Gets SSL certificate error.

**Expected behavior**
Load SSL-encrypted connection.

**Screenshots**
![image](https://user-images.githubusercontent.com/507482/117548238-d500fe00-b001-11eb-8610-c478ce935576.png)

**Server info (please complete the following information):**
 - Linux release: Ubuntu 20.10
 - Server type Raspberry Pi
 - Docker version 20.10.2
 - docker-compose version 1.27.4

**Logs (please send some logs):**
 - letsencrypt container (if related to ssl)
 ```
Creating/renewal sub.domain.com certificates... (sub.domain.com)
[Sat May  8 17:26:39 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sat May  8 17:26:39 UTC 2021] Creating domain key
[Sat May  8 17:26:43 UTC 2021] The domain key is here: /etc/acme.sh/contact@domain.com/sub.domain.com/sub.domain.com.key
[Sat May  8 17:26:43 UTC 2021] Single domain='sub.domain.com'
[Sat May  8 17:26:43 UTC 2021] Getting domain auth token for each domain
[Sat May  8 17:26:45 UTC 2021] Getting webroot for domain='sub.domain.com'
[Sat May  8 17:26:45 UTC 2021] Verifying: sub.domain.com
[Sat May  8 17:26:48 UTC 2021] Pending
[Sat May  8 17:26:51 UTC 2021] Pending
[Sat May  8 17:26:53 UTC 2021] Pending
[Sat May  8 17:26:56 UTC 2021] sub.domain.com:Verify error:Fetching http://sub.domain.com/.well-known/acme-challenge/fWbMyuOsubVTAlGEqNKfyfaRoB92iNt8XUCAUKUB_tY: Timeout during connect (likely firewall problem)
[Sat May  8 17:26:56 UTC 2021] Please check log file for more details: /dev/null
This is going to take a long time
Info: Diffie-Hellman group creation complete, reloading nginx.
Reloading nginx docker-gen (using separate container docker-gen)...
{"message":"Cannot kill container: docker-gen: Container 5c3db04cabfb0fe54ccd6d78c97cbb1f98225da481e248c697e2a45b72e22585 is not running"}
Reloading nginx (using separate container 695715235baf97eded316be9b8b42082903fce2820c61285b513c1d626f81471)...
 ```

**Comment by evertramos** [comment]
Hello @stvhanna!

The ssl was never issued... the logs says it had a timeout, so you might are using Cloudflare proxy or there is some error in the DNS.

**Comment by evertramos** [comment]
Hello @stvhanna!

I am very sorry to inform you that our last commit were done with a bug in the _basescript_ repo, which passed in my test... So, I would like you to try again and see if all will work as expected.
