### ISSUE TITLE
[BUG] Trouble on installation (cannot create network)

### ISSUE THREAD

**Issue by cod3rshotout** [evertramos/nginx-proxy-automation#282]
I'm trying to install `nginx-proxy-automation`, I followed all the steps and run ./fresh-script, the problem's that at the end of installation I get:

 ✘ ERROR There was error when creating the docker network proxy [IPv6 enabled: 'false' ]
 ✘ ERROR   It seems something went wrong running 'local_undo_restore' 

these are the current variables:

    #-----------------------------------------------------------------------
    #
    # https://github.com/evertramos/nginx-proxy-automation
    #
    # NGINX Proxy automation
    #
    # This is the .env file to set up nginx-proxy in your environment
    #
    #-----------------------------------------------------------------------

    #-----------------------------------------------------------------------
    #
    # NGINX-Proxy containers/service
    #
    # The variables below is used to set the containers name for the nginx-proxy
    # and the image version for each service, please note that if you use our script
    # we will replace the service name in docker-compose file with the container name
    #
    NGINX_WEB_SEVICE_NAME=proxy-web-auto
    NGINX_IMAGE_VERSION=stable-alpine

    DOCKER_GEN_SEVICE_NAME=docker-gen-auto
    DOCKER_GEN_IMAGE_VERSION=0.7.6

    LETS_ENCRYPT_SEVICE_NAME=letsencrypt-auto
    NGINX_PROXY_COMPANION_IMAGE_VERSION=2.1

    #-----------------------------------------------------------------------
    #
    # IP address of the external interface
    #
    # The IP address below is used to bind your local services to the internet
    # please make sure you use the correct address otherwise your proxy will not
    # work properly, '0.0.0.0' will work, but we recommend to update this variable
    #
    IPv4=0.0.0.0
    IPv6=::0

    #-----------------------------------------------------------------------
    #
    # Default network name
    #
    # The network name set below is used by the proxy to forward internet requests
    # to the correct containers in your environment, so please make sure to add this
    # network in all docker containers, otherwise it will break the proxy redirection
    #
    NETWORK=proxy

    #-----------------------------------------------------------------------
    #
    # Data path for the nginx-proxy files
    #
    # The variable below will be used to place all files used by the nginx-proxy
    # please consider including this folder to your backup services, once all config
    # files, settings and certificates will be placed here in case you need to recover
    #
    NGINX_FILES_PATH=/home/proxevent/proxy/data

    #-----------------------------------------------------------------------
    #
    # Docker logging settings
    #
    # Logs! Very important, right? But if you do not clean it up, it might causes you
    # issues on disk space over time, so keep in mind to set this log options making sure
    # you will have the least to audit, any further information on that please check the docs
    #
    # https://docs.docker.com/config/containers/logging/configure/
    #
    NGINX_WEB_LOG_DRIVER=json-file
    NGINX_WEB_LOG_MAX_SIZE=4m
    NGINX_WEB_LOG_MAX_FILE=10

    NGINX_GEN_LOG_DRIVER=json-file
    NGINX_GEN_LOG_MAX_SIZE=2m
    NGINX_GEN_LOG_MAX_FILE=10

    NGINX_LETSENCRYPT_LOG_DRIVER=json-file
    NGINX_LETSENCRYPT_LOG_MAX_SIZE=2m
    NGINX_LETSENCRYPT_LOG_MAX_FILE=10

    #-----------------------------------------------------------------------
    #
    # Docker ports that should be binded by the proxy
    #
    # This option were added by a contributor long ago, so might be a very specific case
    # where you might need to change http and https port number, keep in mind that changes
    # on that setting might will break the auto renewing Let's Encrypt certificate services
    #
    DOCKER_HTTP_=80
    DOCKER_HTTPS=443

    #-----------------------------------------------------------------------
    #
    # SSL policy (defaults to Mozilla-Intermediate)
    #
    # This also was added by a contributor which sets the default cipher configuration
    # to the nginx-proxy container, which has the 'Mozilla-Intermediate' as default value
    # plase make sure you take a good look at options in the url below before messing around
    #
    # https://github.com/nginx-proxy/nginx-proxy#how-ssl-support-works
    #
    SSL_POLICY=Mozilla-Intermediate

    #-----------------------------------------------------------------------
    #
    # Let's Encrypt default email
    #
    # You might want to inform a default email to Let's Encrypt certificate once it is
    # a required parameter in order to issue the new certificate. This information will be
    # replaced by the LETSENCRYPT_EMAIL environment varibale present in your docker container
    #
    DEFAULT_EMAIL=info@mydomain.com

**Comment by evertramos** [comment]
@cod3rshotout did you already have this network without ipv6 created? can you run again and send the error? or send us the log at /var/log/basescript.log without sensitive information?

**Comment by cod3rshotout** [comment]
Hi @evertramos thanks for the quick reply, I sent the log on your email, thanks

**Comment by NitashEU** [comment]
I had the same issue. The predefined subnet `172.17.0.0/16` is overlapping with the docker default networks.

I just created the network manually:

`docker network create proxy` and ran fresh-start again.

**Comment by cod3rshotout** [comment]
@NitashEU yeahhh it is working

**Comment by evertramos** [comment]
Thanks @NitashEU!

In case of network error you might set the option of _--ipv4-subnet=_ or _--ipv6-subnet=_ argument option for the _./fresh-install.sh_ script. I will document it as well.
