### ISSUE TITLE
[BUG] There was error when creating the docker network proxy [IPv6 enabled: 'false' ]

### ISSUE THREAD

**Issue by willquill** [evertramos/nginx-proxy-automation#284]
**Check [Discussions](https://github.com/evertramos/nginx-proxy-automation/discussions) to see if there is an answer might help you before opening an issue**

**Describe the bug**
This happens when you enter this: fresh-start.sh

Or when you enter this: ./fresh-start.sh --yes -e your_email@domain --skip-docker-image-check

See this output from the second command:

```
arcana@media:~/proxy/bin$ ./fresh-start.sh --yes -e myemamil@mydomain.com --skip-docker-image-check
⚡ Start execution '/home/arcana/proxy/bin/fresh-start.sh  ✔ success Function 'check_local_env_file'
 ✔ success Function 'check_docker'
 ✔ success Function 'check_running_script'
 ✔ success Function 'starts_initial_check'
 ✔ success Function 'docker_compose_check_service_exists'
 ✔ success Function 'check_docker_nginx_proxy_automation_env_file_exits'
 𝝯 WARNING There is an '.env' file already set to your project, if you continue         
   all settings will be replaced, there is no turn back on that, ok?.
 ✔ success Function 'string_remove_all_special_char_string'
 ✔ success Function 'docker_check_container_exists'
 ✔ success Function 'string_remove_all_special_char_string'
 ✔ success Function 'docker_check_container_exists'
 ✔ success Function 'string_remove_all_special_char_string'
 ✔ success Function 'docker_check_container_exists'
 ✔ success Function 'ip_check_ipv4'
 ✔ success Function 'string_remove_all_special_char_string'
 ✔ success Function 'common_create_folder'
 ✔ success Function 'email_check_is_valid'
 ✔ success Function 'md5_check_checksum'
 ✔ success Function 'md5_check_checksum'
 ✔ success Function 'backup_file'
 ✔ success Function 'backup_file'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'env_update_variable'
 ✔ success Function 'local_update_env_new_site_variables'
 ✔ success Function 'docker_check_network_exists'
Error response from daemon: Pool overlaps with other one on this address space
 ✔ success Function 'docker_network_create'
 ✘ ERROR   There was error when creating the docker network proxy [IPv6 enabled: 'false' ]
 ✘ ERROR   It seems something went wrong running 'local_undo_restore'         
   we will try to UNDO all actions done by this script.         
   Please make sure everything was put it back in place.

```

**To Reproduce**
1. Be on a fresh install of Ubuntu 20.04 server after a full upgrade (sudo apt update && sudo apt full-upgrade)
2. Or be on a fresh install of openSUSE Leap 15.3 server after a full upgrade (sudo zypper dup)
3. I'm not using IPv6 in my local network, and I haven't touched any out of box settings regarding IPv6.
4. Follow the instructions in this repository to clone and run fresh_start.sh.

**Expected behavior**
I expected the fresh start script to run without a hitch.

**Server info (please complete the following information):**
 - Linux release: Ubuntu 20.04 server and openSUSE Leap 15.3 server
 - Server type: Dell R210ii
 - Docker version: On Ubuntu, Docker version 20.10.6, build 370c289 (not sure on Leap version but it was the latest Leap snapshot
 - docker-compose version: On Ubuntu, docker-compose version 1.25.0, build unknown. (not sure on Leap version but it was the latest Leap snapshot)

**Comment by willquill** [comment]
I was able to get fresh_start.sh to run properly after performing several steps.

First I added these lines to /etc/sysctl.conf:
```
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1
```

Then I entered "sudo sysctl -p" and rebooted.

However, I was getting the same error with fresh_start.sh. So I deleted all lines referencing ipv6 within the script, and then I still got the same error.

Finally, I entered "docker network create proxy" and then ran fresh_start again. This time it succeeded.

So I know that "docker network create proxy" is necessary, but I don't know if the steps I ran before were necessary as well.

**Comment by evertramos** [comment]
Hello @willquill!

I noticed that from one issue we had the fix caused more troubled... I just push an update to fix some error on the network creation. Please give a new try and let me know if it fixed it. 

We will improve some more in a few days.

Thanks

**Comment by evertramos** [comment]
@willquill did you manage to test it again?
