### ISSUE TITLE
[BUG] Impossible to generate a new certificat

### ISSUE THREAD

**Issue by Tofdu31** [evertramos/nginx-proxy-automation#285]
Hi All,

I update nginx old project with the new : project nginx-proxy-automation

Actually, is impssible to generate a new certificat. I have an error : 

```
[Fri May 21 07:38:22 UTC 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 23

[Fri May 21 07:38:22 UTC 2021] Could not get nonce, let's try again.

[Fri May 21 07:38:24 UTC 2021] Giving up sending to CA server after 20 retries.

[Fri May 21 07:38:24 UTC 2021] Register account Error: 

grep: /etc/acme.sh/ contact@nbility.fr/ca/acme-v02.api.letsencrypt.org/account.json: No such file or directory

[Fri May 21 07:38:24 UTC 2021] The account url is empty, please run '--update-account' first to update the account info first,

[Fri May 21 07:38:24 UTC 2021] Then try again.

Error: no ACME account was found or registered for  contact@nbility.fr and https://acme-v02.api.letsencrypt.org/directory, certificate creation aborted.
```

I have 4 sub-domains and is Ok. But for a new project (Wordpress or another) i have this error.

Exemple for a sub-domain : exemple.domain.com

If I test with the script nginx-proxy-automation/bin/ssl_test.sh I don't have a problem and my sub-domain is ok with a new certificate Let's Encrypt.

For the parameters with the domain manager (OVH) I did not need to make any modifications because I am using a subdomain which was already configured for an old project.

My docker-compose-yml and .env is ok.

```
# Host
DOMAINS=blabla.domain.com
VIRTUAL_HOST=blabla.domain.com
LETSENCRYPT_HOST=blabla.domain.com
LETSENCRYPT_EMAIL=contact@domain.com
#
# Network name
#
# Your container app must use a network conencted to your webproxy
# https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
#
NETWORK=proxy
```
This is a variable in my docker-compose.yml : 
```
      - VIRTUAL_HOST= ${VIRTUAL_HOST}
      - LETSENCRYPT_HOST= ${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL= ${LETSENCRYPT_EMAIL}
```

For the tests, I changed the name of the subdomain and I have the same error.

Thank you all for your help and don't hesitate to ask me for more information.

I can in PM provide additional, more confidential information.

Have a nice day

Christophe

PS : si vous êtes français, ça sera plus facile pour moi :)

**Comment by evertramos** [comment]
Did you follow this guide:

https://github.com/evertramos/nginx-proxy-automation/blob/master/docs/upgrade-guide.md

I can talk a little and understand french... but not really write it.

**Comment by Tofdu31** [comment]
I deleted the old folder and performed a fresh install.
What I don't understand is that I relaunched containers (example with Wordpress) and I have no problem. On the other hand, if I want to launch new containers with a domain name that I used before, then it doesn't work.

How can I force the regeneration of a certificate for eg blabla.fr

**Comment by evertramos** [comment]
Did you try to add VIRTUAL_PORT to the environment?

https://github.com/evertramos/nginx-proxy-automation#further-options
