### ISSUE TITLE
[BUG] Network proxy declared as external, but could not be found.

### ISSUE THREAD

**Issue by Nuube** [evertramos/nginx-proxy-automation#291]
When running fresh-start, I got:

```
....
✔ success Function 'local_update_docker_compose_file'
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
ERROR: Network proxy declared as external, but could not be found. Please create the network manually using `docker network create proxy` and try again.
 ✔ success Function 'docker_compose_start'
 ✘ ERROR   There was an error starting the service at '/home/docker/proxy/bin/../'
....

```

**Screenshots**
![image](https://user-images.githubusercontent.com/25643142/121594458-5f8faf80-ca3d-11eb-84a0-0f13504a05cb.png)

**Server info (please complete the following information):**
 - Linux release: Debian Buster
 - Server type: OMV
 - Docker version: 20.10.6
 - docker-compose version : 1.28.4

**Comment by evertramos** [comment]
did you try to create the network by yourself and start the environment?

**Comment by Nuube** [comment]
No I stopped here because it was to late yesterday. I mostly wanted to point out there is a glitch in the script. 
I'll try over the weekend and let you know.

**Comment by Nuube** [comment]
Ok,  I created the network in docker, deleted the whole directory tree and started over, and the container did start.

**Comment by tbarbette** [comment]
I followed the main README.md guidelines and got the same error. If the network must be created manually, shouldn't it be part of the quickstart documentation?
