### ISSUE TITLE
[BUG] Multiple php instances on the same network create conflicts

### ISSUE THREAD

**Issue by cod3rshotout** [evertramos/nginx-proxy-automation#298]
I'm using `php-fpm` which runs for default on the port `9000`. The problem's that I have other docker container based on `php-fpm`, so I need to change the default port to another one, in order to not confuse `nginx`.

This is my `Dockerfile`:

    FROM php:8.0.2-fpm-alpine
    
    WORKDIR /var/www/html

    CMD ["php-fpm"]
    
    EXPOSE 9001

Inside my `docker-compose` file I have this configuration:

    version: '3.9'
    
    services:
    
      php-fpm:
        container_name: app
        restart: always
        build:
          context: .
          dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
          - ./src:/var/www/html
          - ./docker/php-fpm/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
          - ./src/public:/app/public
          - ./src/writable:/app/writable
    
      nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        volumes:
          - ./src:/var/www/html
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./docker/nginx/sites/:/etc/nginx/sites-available
          - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
          - php-fpm
        environment:
          VIRTUAL_HOST: ${HOST}
          LETSENCRYPT_HOST: ${HOST}
          LETSENCRYPT_EMAIL: ${EMAIL}

    networks:
      default:
        external:
          name: proxy

    volumes:
      dbdata:

as you can see I use the network "proxy" which is the same for each application that I run over proxy automation. Also, I copied the configuration of php-fpm "www.conf" and I change this line:

    ; The address on which to accept FastCGI requests.
    ; Valid syntaxes are:
    ;   'ip.add.re.ss:port'    - to listen on a TCP socket to a specific IPv4 address on
    ;                            a specific port;
    ;   '[ip:6:addr:ess]:port' - to listen on a TCP socket to a specific IPv6 address on
    ;                            a specific port;
    ;   'port'                 - to listen on a TCP socket to all addresses
    ;                            (IPv6 and IPv4-mapped) on a specific port;
    ;   '/path/to/unix/socket' - to listen on a unix socket.
    ; Note: This value is mandatory.
    listen = 127.0.0.1:9001

I've specified to use the port 9001 instead of 9000

The file `default.conf` available within `conf.d` folder contains this:

    upstream php-upstream {
        server php-fpm:9001;
    }

the problem's that for some reason, when I load my site I get the error 500. So this means that the stream doesn't send any signal. If I change to port `9000` everything works, but the stream is wrong 'cause it's the content of another application.

This is what I see in the container list:

<img src="https://i.imgur.com/rSAm4ve.jpg">
<img src="https://i.imgur.com/ADHxHu4.jpg">

if I use the port 9000, I get the content of the other application displayed. 

This is the log displayed by nginx when I tried to load the site:

    upstream server temporarily disabled while connecting to upstream, client: 192.168.16.4, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.17:9001

What am I doing wrong?
Could you please help?

Kind regards

**Comment by Graf-Zahl** [comment]
In principal I have the same problem I think.
I have 2 docker-compose files in two dirs, which both creates 3 services (nginx, django, postgresql), two domains. When I call example1.com I get Http400, then refresh, I get content of the django service of example2.com.
The service names in both files are the same and both use the webproxy. Maybe somewhere here the problem?

**Comment by Graf-Zahl** [comment]
Yes, it was, I think.
Use your container name for addressing it: 
`upstream php-upstream {
    server unique-container-name:9001;
}`

**Comment by cod3rshotout** [comment]
@Graf-Zahl  This happen also with PhpMyAdmin, not only with upstream, I opened an issue here: 

https://stackoverflow.com/questions/68066555/multiple-phpmyadmin-instances-create-conflict

**Comment by Graf-Zahl** [comment]
I'm not an expert, but you `listen ` on ` 127.0.0.1:9001` at the same proxy network. just use the unique container name instead of the internal IP / the "php-fpm" service name

**Comment by cod3rshotout** [comment]
I managed to fix this simply change the container name service and the port
