### ISSUE TITLE
Usage with Cloudflare Tunnels

### ISSUE THREAD

**Issue by avidsapp** [evertramos/nginx-proxy-automation#302]
**Is your feature request related to a problem? Please describe.**
I'm attempting to use this with Cloudflare Tunnels. The tunnel works fine with an undockerized NGINX reverse proxy and multiple domains. Cloudflared only provides a CNAME for the domain, so this may be the holdup. Encryption at the host isn't necessary as traffic to Cloudflare is still encrypted.

**Describe the solution you'd like**
Insight on how to forward correctly through the tunnel to the dockerized proxy

**Describe alternatives you've considered**
- DNS verification via Let's Encrypt.
- [Nginx-proxy/nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) without Let's Encrypt
- Commenting out `LETSENCRYPT_HOST` to disable SSL in application environments

**Comment by avidsapp** [comment]
Commenting out `LETSENCRYPT_HOST`, exposing only port 80, and ensuring the network matches the application network allows this to function behind Cloudflare Tunnels

**Comment by evertramos** [comment]
Also check #238
