### ISSUE TITLE
Multiple domain name for same container

### ISSUE THREAD

**Issue by syntaxgirl** [evertramos/nginx-proxy-automation#312]
Hi, I need to setup multiple domain names for the same nginx. Is this possible with nginx proxy automation?

Currently I set this up inside docker-compose file
```
        hostname: example.com
        environment:
            - VIRTUAL_HOST=example.com
            - LETSENCRYPT_HOST=example.com
            - LETSENCRYPT_EMAIL=email@example.com
```
But I need to set more than 1 domain name for the same service (nginx). Anyone have some idea?

**Comment by evertramos** [comment]
```
hostname: example.com
        environment:
            - VIRTUAL_HOST=example.com,example2.com,example3.com,example4.com,example5.com
            - LETSENCRYPT_HOST=example.com,example2.com,example3.com,example4.com,example5.com
            - LETSENCRYPT_EMAIL=email@example.com
```

**Comment by FractalMind** [comment]
>     environment:
>             - VIRTUAL_HOST=example.com,example2.com,example3.com,example4.com,example5.com
>             - LETSENCRYPT_HOST=example.com,example2.com,example3.com,example4.com,example5.com
>             - LETSENCRYPT_EMAIL=email@example.com

Can we make this process dynamic without restarting the server?

I would like to add exemple6.com on-the-fly without recreating the everything. Is it possible?

**Comment by evertramos** [comment]
Yes just run a compose restart in your service containers (NOT THE PROXY) and it will not stop it, just refresh the virtual hosts: 

```bash
docker-compose restart 
```

**Comment by FractalMind** [comment]
> Yes just run a compose restart in your service containers (NOT THE PROXY) and it will not stop it, just refresh the virtual hosts:
> 
> ```shell
> docker-compose restart 
> ```

I'm sorry, I just want to confirm this with you. 

I have your 3 containers:
```
docker-gen-auto: jwilder/docker-gen:0.7.3
letsencrypt-auto: jrcs/letsencrypt-nginx-proxy-companion:2.0
proxy-web-auto: nginx:stable-alpine

//+plus mine:
myContainer: nimmis/apache-php7
```

You suggest to 
`docker-compose restart`

```
proxy-web-auto is up-to-date
letsencrypt-auto is up-to-date
Recreating myContainer ... 
Recreating myContainer ... done
```
But when it restarts myContainer there's a HUGE downtime of like 5 seconds. Because the container needs to restart and setup the webserver inside the myContainer. I am getting this right?

**Comment by evertramos** [comment]
Hello @FractalMind,

In fact, you are right. If you do a restart it will rebuild the container, so you will have a downtime. So, what are the options?

I found this tread:

https://github.com/nginx-proxy/nginx-proxy/issues/1051

There is a suggestion to add nginx conf files and you might achieve what you need, but even though, you might should try the wildcard domains, it might be a better way to do it.

Also you might try to add a default domain (container) for the proxy, this might be used in your case, but I am not sure, never tested.

Sorry not having enough information to help you out with.

Let us know if you got through this!

**Comment by FractalMind** [comment]
> There is a suggestion to add nginx conf files and you might achieve what you need, but even though, you might should try the wildcard domains, it might be a better way to do it.
> 
> Also you might try to add a default domain (container) for the proxy, this might be used in your case, but I am not sure, never tested.


Thank you @evertramos for your quick answer. I can't believe I didn't think about the wildcards sooner.

But I can't find a way to create a wildcard with your system. I tried
```
VIRTUAL_HOST=*.web.mydomain.com
LETSENCRYPT_HOST=*.web.mydomain.com
```
It doesn't work.
Let's say your system is not designed to generate wildcards certificates is there a way I can add custom certificates into the _/data/certs_   
I tried to generate seft-sign certificates and place them into _/data/certs_  
But it still won't recognize the domain I get a 503

**Comment by evertramos** [comment]
Please check here:

https://github.com/nginx-proxy/nginx-proxy#wildcard-hosts

**Comment by FractalMind** [comment]
> Please check here:
> 
> https://github.com/nginx-proxy/nginx-proxy#wildcard-hosts

Thank you... took me a while figuring a solution but for the following people... You can manually generate a wildcard certificate with Letsencrypt

apt install -y letsencrypt
certbot certonly --manual --agree-tos --preferred-challenges dns -d 'mydomain.com,*.mydomain.com'

 place them it in the **_data/cert_** folder and create a symlink to autodetect the certificate for the wildcard. 
Please see this: https://github.com/nginx-proxy/nginx-proxy/issues/1273#issuecomment-566982289

**Comment by evertramos** [comment]
Nice @FractalMind! But please remember to set this autorenew using certibot in your cron or supervisor, so within 3 month period you don't get an expired certificate. Thanks for you reply.
