### ISSUE TITLE
413 Nginx - Entity too large only with certain files

### ISSUE THREAD

**Issue by cod3rshotout** [evertramos/nginx-proxy-automation#332]
I'm using `Nginx` which have this configuration:

    user  nginx;
    worker_processes  4;
    
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    
    events {
        worker_connections  1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        client_max_body_size 100M;
    
        access_log  /var/log/nginx/access.log;
        # Switch logging to console out to view via Docker
        #access_log /dev/stdout;
        #error_log /dev/stderr;
    
        sendfile        on;
        keepalive_timeout  65;
        
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-available/*.conf;
    }

and also, `php-fpm` actually contains the following `php.ini` settings:

    upload_max_filesize = 100M
    max_file_uploads = 20
    max_input_time = 60
    memory_limit = 32M

When I upload images with a size of 7Mb no issue appear, but when I upload a file with 1200Kb with `.mp3` extension, I get:

>413 - Entity Too Large

this happen only with audio files, someone could explain me why?

Seems like `Nginx` cannot read the file weight from certain extension files.

**Comment by evertramos** [comment]
Hello @cod3rshotout, sorry miss your issue for such a long time... hope you've solve it. 

here are some related:

#81 - https://github.com/evertramos/nginx-proxy-automation/issues/81

#207 - https://github.com/evertramos/nginx-proxy-automation/issues/207
