### ISSUE TITLE
Help with 502 error

### ISSUE THREAD

**Issue by Pyroseza** [evertramos/nginx-proxy-automation#350]
For some reason I'm hitting a 502 error:

```
502 Bad Gateway
nginx/1.20.2
```

I have no idea what went wrong, I have just redone my app container (stopped and removed) then rebuilt it and redeployed.

How can I force it to cleanly reload my config?

I've got nothing special it's just a simple django app listening on port 8000.

**Comment by evertramos** [comment]
logs? steps to reproduce? your settings? ....

**Comment by Pyroseza** [comment]
I don't what went wrong, I'd just like to know what I can do to completely flush out any kind of cache, I've tried deleting and recreating the containers but the problem persists

**Comment by evertramos** [comment]
@Pyroseza to flush everything, delete the 'proxy' folder and start over... with fresh-instal.sh.

**Comment by Pyroseza** [comment]
That's what I already did, I just confirmed by doing it again, and still the same thing...

**Comment by Pyroseza** [comment]
It seems like the problem is with nginx, and no matter how many times I delete and recreate everything it does not work

```
2022/03/25 08:20:16 [error] 94#94: *30 no live upstreams while connecting to upstream, client: <REDACTED_IP>, server: <REDACTED_FQDN>, request: "GET / HTTP/2.0", upstream: "http://<REDACTED_FQDN>/", host: "<REDACTED_FQDN>"
<REDACTED_FQDN> <REDACTED_IP> - - [25/Mar/2022:08:20:16 +0000] "GET / HTTP/2.0" 502 157 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15"
2022/03/25 08:20:25 [error] 94#94: *31 no live upstreams while connecting to upstream, client: <REDACTED_IP>, server: <REDACTED_FQDN>, request: "GET / HTTP/1.1", upstream: "http://<REDACTED_FQDN>/", host: "<REDACTED_FQDN>"
<REDACTED_FQDN> <REDACTED_IP> - - [25/Mar/2022:08:20:25 +0000] "GET / HTTP/1.1" 502 157 "-" "Go-http-client/1.1"
<REDACTED_FQDN> <REDACTED_IP> - - [25/Mar/2022:08:20:31 +0000] "GET / HTTP/1.1" 301 169 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"
2022/03/25 08:20:32 [error] 94#94: *33 no live upstreams while connecting to upstream, client: <REDACTED_IP>, server: <REDACTED_FQDN>, request: "GET / HTTP/1.1", upstream: "http://<REDACTED_FQDN>/", host: "<REDACTED_FQDN>"
<REDACTED_FQDN> <REDACTED_IP> - - [25/Mar/2022:08:20:32 +0000] "GET / HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"
```

**Comment by Pyroseza** [comment]
And just before you ask, yes I checked that my container is on the `proxy` network, and yes ai check that my env variables are set correctly when starting up

**Comment by evertramos** [comment]
if you don´t post logs, nginx.conf, your docker-compose.yml neither I or anybody would be able to help you duce... @Pyroseza 

P.S.: If I don´t answer anymore it is because there is not enogh information.... Cheers!

**Comment by Pyroseza** [comment]
@evertramos  Everything is the defaults, nothing is special for my deployment, that's why I'm asking for your help here

**Comment by Pyroseza** [comment]
Btw logs are above that's the only thing that happens when I try access my https URL
