### ISSUE TITLE
[BUG] Docker hub API v1 not working anymore

### ISSUE THREAD

**Issue by Twois** [evertramos/nginx-proxy-automation#362]
**Check [Discussions](https://github.com/evertramos/nginx-proxy-automation/discussions) to see if there is an answer might help you before opening an issue**

**Describe the bug**
The docker hub API v1 is dead as of 5th of September. 

https://www.docker.com/blog/docker-hub-v1-api-deprecation/

**To Reproduce**
run the fresh start script and it will drop docker image not exist error.

**Comment by evertramos** [comment]
Hello @Twois,

Thanks for your issue. In fact if you decide to run the fre, and in fact the docker hub
