### ISSUE TITLE
[BUG] Error starting the service 

### ISSUE THREAD

**Issue by mazembo** [evertramos/nginx-proxy-automation#378]
**Check [Discussions](https://github.com/evertramos/nginx-proxy-automation/discussions) to see if there is an answer might help you before opening an issue**

**Describe the bug**
installation is not going to completion. Stopping with an error.

**To Reproduce**
follow how to start guide
1. Clone this repository using the option --recurse-submodules ⚠️
git clone --recurse-submodules https://github.com/evertramos/nginx-proxy-automation.git proxy 
We use submodule for [basescript](https://github.com/evertramos/basescript)

2.🚀 Run the script 'fresh_start.sh' from the ./proxy/bin folder
cd proxy/bin && ./fresh-start.sh --yes -e your_email@domain --skip-docker-image-check

**Expected behavior**
Three running containers.

**Screenshots**
If the error is in one of the scripts, an screen show will help a lot to identify which part of the script the error occurred. 

![nginx-prox-installation-error4](https://user-images.githubusercontent.com/47649/230717435-ef07c0d9-6a0d-4f63-9773-04d6e93242cc.JPG)
![nginx-prox-installation-error3](https://user-images.githubusercontent.com/47649/230717442-65287ba9-ca0b-48cd-90a8-112a85387568.JPG)
![nginx-prox-installation-error2](https://user-images.githubusercontent.com/47649/230717445-efcb4b06-0966-4141-9a62-f9f5889e6f8d.JPG)

![nginx-prox-installation-error](https://user-images.githubusercontent.com/47649/230717468-b95d70a6-5431-4620-8a09-0b4c5ec44018.JPG)

**Server info (please complete the following information):**
 - Linux release: Amazon linux 2 and ubuntu 19.10
 - Server type: ec2 and bare metal server 
 - Docker version 20.10
 - docker-compose version 2.2.3

**Logs (please send some logs):**
 - nginx container
 - letsencrypt container (if related to ssl)

**Additional context**

**Comment by evertramos** [comment]
Hello @mazembo,

Thanks for your message!

The first error tells you that the service could not be started, it tells me that your 'docker compose' was called but returned an error. So, please consider running manually 'docker compose up -d'  in root folder where you cloned this repo.

As for your docker versions... you don´t have an updated version of docker compose installed. Docker already comes with 'compose', so please refer to:

- https://docs.docker.com/compose/install/linux/#install-using-the-repository

Or just use 'docker-compose up -d' to see if all services will come up correctly. 

Let me know if it worked.
