### ISSUE TITLE
[BUG] nginx: [emerg] unknown directive "http2" in web container

### ISSUE THREAD

**Issue by Andargor** [evertramos/nginx-proxy-automation#383]
**Check [Discussions](https://github.com/evertramos/nginx-proxy-automation/discussions) to see if there is an answer might help you before opening an issue**

**Describe the bug**

The web container dies repeatedly due to an error in configuration, see below.

To fix, I reverted to the previous commit of `nginx.tmpl`

**To Reproduce**
1. `docker compose up -d`

**Expected behavior**
Not dying

**Screenshots**
See logs below

**Server info (please complete the following information):**
 - Linux release: Ubuntu 22.04 LTS
 - Server type: Intel PC
 - Docker version 24.0.5
 - docker-compose version (plugin)
 
**Logs (please send some logs):**
Web container
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/07/31 03:45:32 [emerg] 1#1: unknown directive "http2" in /etc/nginx/conf.d/default.conf:82
nginx: [emerg] unknown directive "http2" in /etc/nginx/conf.d/default.conf:82
```
Letsencrypt container
```
2023/07/31 03:49:10 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
2023/07/31 03:49:10 Received event start for container 9335245a3210
2023/07/31 03:49:10 Received event die for container 9335245a3210
2023/07/31 03:49:10 Received event start for container 9335245a3210
2023/07/31 03:49:11 Received event die for container 9335245a3210
2023/07/31 03:49:12 Received event start for container 9335245a3210
2023/07/31 03:49:12 Received event die for container 9335245a3210
2023/07/31 03:49:13 Received event start for container 9335245a3210
2023/07/31 03:49:14 Received event die for container 9335245a3210
```

**Comment by evertramos** [comment]
Hello @Andargor, 

Thanks for the heads up, I had fixed manually but did not commit to the repo, and the idea is always keep track with [nginx-proxy repo](https://github.com/nginx-proxy/nginx-proxy).

nginx template reverted.

**Comment by evertramos** [comment]
Yes we use stable-alpine (https://github.com/evertramos/nginx-proxy-automation/blob/5060f03f9ca941d8c39a5c6c0926b214d457632c/.env.sample#L31), so, I will wait nginx to build it, but looks weird these versions of alpine without the stable, once the current stable is in 1.25.
