### ISSUE TITLE
[BUG] SPA History Mode sub route 404

### ISSUE THREAD

**Issue by dolphin836** [evertramos/nginx-proxy-automation#395]
When our single-page application uses History mode routing, there is no problem in jumping to the sub-route from the home page, but a 404 error will occur when the sub-route is refreshed. Can it be solved by modifying the Nginx configuration file and adding
```
try_files $uri $uri/ /index.html
```
Where to add it specifically?

**Comment by evertramos** [comment]
I quiet didn´t understand what you mean... if you want to change the nginx settings that is not in our documentation, check the nginx-proxy documentation https://github.com/nginx-proxy/nginx-proxy.
